[package]
name = "mister"
version = "0.1.3"
authors = ["herojan"]

[dependencies]
mustache = "0.9.0"
structopt = "0.2.15"
failure = "0.1.5"
exitfailure = "0.5.1"
serde = "1.0.89"
serde_yaml = "0.8.8"
serde_derive = "1.0.89"